### PR TITLE
Fix indentation time confing

### PR DESCRIPTION
**Pull request by kaffeekanne**
Small fix of indention visible when usig `/prefs`. Also first PR! \o/

### CODE REVIEW

**Comment by jubalh** [comment]
Nice!

Now you should update the commit message `git commit --amend`. And use `Fix indention for time confing` instead of `Update console.c`. Then do `git push -f yourremotename`.

**Comment by jubalh** [comment]
Now it looks like "John Doe" committed :-)
Also you fixed one typo in 'config' (before 'comfig') and added a new one instead 'confing'.

**Comment by kaffeekanne** [comment]
next time i will post an issue again 😫

**Comment by jubalh** [comment]
Better. Now we have `indention` instead of `indentation` though :-)

**Pull request merged**
