### PR TITLE
Occupants header char

### PR DESCRIPTION
**Pull request by jubalh**
Regards https://github.com/boothj5/profanity/issues/690

### CODE REVIEW

**Comment by kaffeekanne** [comment]
Works for me, no idea, what travis complains about. Theming not tested, as i have not created any custom theme before.

#1072 and #1074 need to be mentioned in documentation, maybe as an checklist issue forget about it?

**Comment by jubalh** [comment]
> #1072 and #1074 need to be mentioned in documentation, maybe as an checklist issue forget about it?

What do you mean by this? Mentioned where exactly?

**Comment by kaffeekanne** [comment]
Are http://profanity.im/themes.html and http://profanity.im/reference.html#occupants autogenerated or hand made in https://github.com/boothj5/www_profanity_im ?

**Comment by jubalh** [comment]
Like mentioned before https://github.com/boothj5/www_profanity_im contains everything you need. I'm unsure what you mean with autogenerated. It's not markdown transformed to html if that's what you mean. We write the html by hand. Otherwise the script/markdown would be in there and not plain html pages ;)

**Comment by jubalh** [comment]
I created the commit to change the docu now. But I guess in the future I'll do it only once the tracker issue is done. So I only have to edit the file once :-)

**Pull request merged**
