### PR TITLE
Nicks containig spaces need to be quoted

### PR DESCRIPTION
**Pull request by rjc**

### CODE REVIEW

**Comment by jubalh** [comment]
Please change the commit message.

Usually the first line is a quick description/header. Then comes an empty line and then some more explanations.
For a good example see: https://github.com/boothj5/profanity/commit/7f65aaa9a2ba1e7d9fe182cc18938fa39462e095

**Comment by rjc** [comment]
I'm not sure if this would suffice - please feel free to squash them at your end :^)

**Comment by jubalh** [comment]
Actually a `git commit --amend` and `git push -f` is what would have been nice. Then you could have just changed the commit message of the commit you already created ;)

**Comment by jubalh** [comment]
Merged with a97202ace67673bc884e9cdf3c755783cec47407

**Comment by rjc** [comment]
@jubalh, I've done `git commit --amend` but hadn't used `-f` with `git push` and it asked me to merge, which I did - I'll use `git push -f` next time ;^)

Ta!

**Pull request closed without merging**
