### PR TITLE
Use custom format string for time preference

### PR DESCRIPTION
**Pull request by incertia**
Exactly as described in title. Any string that `g_date_time_format` takes is usable. This solves #493.

### CODE REVIEW

**Comment by boothj5** [comment]
There is also an 'off' setting, so perhaps the command could be:

```
/time set format
/time off
```

Also the width of the time string is used to calculate the word wrapping indent at https://github.com/boothj5/profanity/blob/master/src/ui/window.c#L962

**Comment by incertia** [comment]
You should set the time format to the empty string to turn off formatting. #500 fixes the problem of not being able to send empty strings as arguments to non-freetext commands.

I'll see if I can make something up for calculating the indent width.

**Comment by incertia** [comment]
Sorry for lack of activity. Decided to go with the set/off approach because the empty argument fix was never pulled. Fixed indent problems, applied same logic to statusbar, and probably fixed any indent-similar issues with the statusbar.

**Comment by boothj5** [comment]
Finally got around to merging this request after some testing.  Very useful feature thanks.

**Pull request merged**
