### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by jubalh**
some small warnings/errors fixed.

### CODE REVIEW

**Comment by boothj5** [comment]
The patch currently isn't compiling, you can see the error at the travis build above.

Also, since you are making the function prototypes consistent, I'd rather the `*` was next to the return type of the function, e.g/:

`gchar* get_some_string(void)`

Rather than after a space:

`gchar * get_some_string(void)` 

I'm aware this is personal preference, I find it more readable this way.

**Comment by jubalh** [comment]
Fixed the build and adapted the style.

We still have

```
Login failed.prof_output_regex("stabber@localhost logged in successfully, .+online.+ \\(priority 0\\)\\.")

tests/functionaltests/proftest.c:252: error: Failure!

[  FAILED  ] connect_jid_requests_roster
```

But I hope this doesn't have to do anything with my changes.

**Comment by boothj5** [comment]
I'm now getting the same test failure in master on travis, but it passes locally. I'll investigate and merge this pull request once I've figured out why the test is failing on travis.

**Comment by boothj5** [comment]
Fixed the travis build. Turns out something has changed in travis which doesn't allow connecting to `localhost` in functional tests, instead the ip address is required (`127.0.0.1`) boothj5/profanity@9c08211119605d744e75148ce7bcae64b7cffd7a

Regarding pointer styles in the patch. We've agreed on:

**Return type:**
`char* somefunc(void);`
**Arguments:**
`void somefunc(char *thing);`

We didn't talk about the `const` qualifier though. I think the following is fine, which you've added:

**Pointer to constant value:**
`void somefunc(const char *thing);`

However I'm not sure about the following change:

**Constant pointer to constant value:**
`void somefunc(const char* const thing);`

I.e. having the `*` next to `char`.  Since in all other argument cases we keep the `*` close to `thing`, I think this should possibly be:

`void somefunc(const char *const thing);`

So reading backwards... `thing` is a "constant pointer" to a "char which is constant", and it's closer to the other argument pointer styles.

Sorry for being pedantic and I'm aware the existing code doesn't really follow any pattern, but since this commit is mostly about adding consistent style it's probably worth agreeing on.  What do you think?

**Comment by jubalh** [comment]
Done ;)

**Comment by boothj5** [comment]
There's another compile error:

```
src/chat_session.c:121:1: error: conflicting types for ‘chat_session_recipient_paused’
 chat_session_recipient_paused(const char * const barejid, const char * const resource)
 ^
In file included from src/chat_session.c:41:0:
src/chat_session.h:57:6: note: previous declaration of ‘chat_session_recipient_paused’ was here
 void chat_session_recipient_paused(const char  const barejid, const char *const resource);
```   

Also there's a few inconsistencies with the pointer style changes:

From the diff:

src/contact.h:
```
-void p_contact_set_last_activity(const PContact contact, GDateTime *last_activity);
+void p_contact_set_last_activity(const PContact contact, GDateTime*last_activity);
```
src/log.h
```
-void log_debug(const char * const msg, ...);
-void log_info(const char * const msg, ...);
-void log_warning(const char * const msg, ...);
-void log_error(const char * const msg, ...);
+void log_debug(const char* const msg, ...);
+void log_info(const char* const msg, ...);
+void log_warning(const char* const msg, ...);
+void log_error(const char* const msg, ...);
```
```
-GSList * chat_log_get_previous(const gchar * const login,
-    const gchar * const recipient);
+GSList* chat_log_get_previous(const gchar *const login,
+    const gchar* const recipient);
```

src/roster_list.h
```
-gboolean roster_contact_offline(const char * const barejid,
-    const char * const resource, const char * const status);
+gboolean roster_contact_offline(const char *const barejid,
+    const char* const resource, const char *const status);
```
```
-gboolean roster_add(const char * const barejid, const char * const name, GSList *groups,
-    const char * const subscription, gboolean pending_out);
+gboolean roster_add(const char *const barejid, const char *const name, GSList *groups,
+    const char* const subscription, gboolean pending_out);
```

src/window_list.h
```
-ProfWin * wins_new_muc_config(const char * const roomjid, DataForm *form);
+ProfWin* wins_new_muc_config(const char *const roomjid, DataForm*form);
```

**Comment by boothj5** [comment]
I can fix the small points above and merge the request if you don't have time (or are bored of this pull request!)

**Comment by jubalh** [comment]
Sorry, I didn't find time. But did it now!
Also sorry for the mistakes ;)

**Comment by boothj5** [comment]
Merged, thanks.

**Pull request merged**
