### PR TITLE
XEP-0280 support (Message carbons)

### PR DESCRIPTION
**Pull request by olivierlemoal**
Implements XEP-0280 : http://xmpp.org/extensions/xep-0280.html
(Issue #329)

Use as follow :

/carbons on|off                                                                                  
                                                                              
- Enable or disable message carbons.                                                               
- The message carbons feature ensures that both sides of all                                       
conversations are shared with all the user's clients that implement                              
this protocol.

Default : off

### CODE REVIEW

**Comment by olivierlemoal** [comment]
Well, it looks like it breaks the tests suite.
I'll have a look...

**Comment by olivierlemoal** [comment]
I'll add some tests later on.

**Comment by boothj5** [comment]
I've manually tested the basics and seems to be working fine.

I'll do some more testing (effect on OTR conversations, chat sessions and chat states etc) once the 0.4.6 release is out, and will aim to include this in 0.4.7.

Thanks.

**Comment by boothj5** [comment]
Now 0.4.6 is finally out, I've merged this into a branch for some testing.  Will keep you updated.

**Comment by boothj5** [comment]
Changes are now merged into master.  I've added some error handling, and added the <private> element to OTR messages as per: http://xmpp.org/extensions/xep-0280.html#avoiding

Thanks again for the addition, it's a very cool feature.

**Pull request merged**
